FROM quay.io/azavea/django:1.11-python3.6-slim

# Install OS-level dependencies for Grout
RUN apt-get update
RUN apt-get -y autoremove && apt-get install -y \
	libgeos-dev \
	binutils \
	libproj-dev \
	gdal-bin \
	git

COPY . /opt/grout
WORKDIR /opt/grout

RUN pip install -e .

ENTRYPOINT ["bash", "-c"]
CMD ['django-admin', 'makemigrations']
