"""Initial migration

Revision ID: 446a73f9070
Revises: 
Create Date: 2015-04-15 17:32:50.294325

"""

# revision identifiers, used by Alembic.
revision = '446a73f9070'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label', 'version', name='_item_version_uc'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('item_schema_idx', 'object_schemas', ['schema'], unique=False, postgresql_using='gin')
    op.create_table('record_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_type', 'version', name='_record_version_uc')
    )
    op.create_index('record_schema_idx', 'record_schemas', ['schema'], unique=False, postgresql_using='gin')
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('occurred_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('geo', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('schema_id', sa.Integer(), nullable=True),
    sa.Column('json_data', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['record_schemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('json_data_idx', 'records', ['json_data'], unique=False, postgresql_using='gin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('json_data_idx', table_name='records')
    op.drop_table('records')
    op.drop_index('record_schema_idx', table_name='record_schemas')
    op.drop_table('record_schemas')
    op.drop_index('item_schema_idx', table_name='object_schemas')
    op.drop_table('object_schemas')
    ### end Alembic commands ###
