# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 17:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonb_field_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonbmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
