#!/bin/bash

# Most reliable way to get the path for this script.
# h/t: https://stackoverflow.com/questions/192292/bash-how-best-to-include-other-scripts/12694189#12694189
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]];
then
    DIR="$PWD"
fi

# Load common configs for this script.
source "${DIR}/_config.sh"

function usage() {
    echo -n "Usage: $(basename "$0") {build}

Updates repo state using docker-compose.

Options:
    -h --help    Display this help text
    build        Update container images
"
}

function buildcontainers() {
    # Build containers.
    docker-compose build
}

function run_all_updates() {
    buildcontainers
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ -z "$1" ]
    then
        # No arguments -- run all update functions.
        run_all_updates
    else
        case "${1:-}" in
            -h|--help)  usage ;;
            build)      buildcontainers ;;
            *)          echo "ERROR: command '${1}' is not valid." && echo && usage && exit 1
        esac
    fi
fi
