# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0023_remove_weather_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='city_district',
        ),
        migrations.RemoveField(
            model_name='record',
            name='county',
        ),
        migrations.RemoveField(
            model_name='record',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='record',
            name='road',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.AlterField(
            model_name='boundary',
            name='color',
            field=models.CharField(default='blue', max_length=64),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='source_file',
            field=models.FileField(upload_to='boundaries/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('COMPLETE', 'Complete')], default='PENDING', max_length=10),
        ),
    ]
