# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 20:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0024_auto_20180716_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtype',
            name='geometry_type',
            field=models.CharField(choices=[('point', 'Point'), ('polygon', 'Polygon'), ('multipolygon', 'MultiPolygon'), ('linestring', 'LineString'), ('none', 'None')], default='point', max_length=12),
        ),
        migrations.AddField(
            model_name='recordtype',
            name='temporal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='record',
            name='occurred_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='occurred_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
