# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 13:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grout', '0024_auto_20180716_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibleRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('archived', models.BooleanField(default=False)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grout.RecordSchema')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('archived', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_text', models.CharField(blank=True, max_length=200, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grout.RecordSchema')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PolygonRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('archived', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('location_text', models.CharField(blank=True, max_length=200, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grout.RecordSchema')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TemporalFlexibleRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('archived', models.BooleanField(default=False)),
                ('occurred_from', models.DateTimeField()),
                ('occurred_to', models.DateTimeField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grout.RecordSchema')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TemporalPointRecord',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='grout.Record')),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=('grout.record',),
        ),
        migrations.CreateModel(
            name='TemporalPolygonRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('archived', models.BooleanField(default=False)),
                ('occurred_from', models.DateTimeField()),
                ('occurred_to', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('location_text', models.CharField(blank=True, max_length=200, null=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grout.RecordSchema')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
